### ISSUE TITLE
Discord invite link not working

### ISSUE THREAD

**Issue by RDMurray** [openscape-community/openscape#10]
When trying to join the discord server I get the message "This invite may be expired or you might not have permission to join."

**Comment by steinbro** [comment]
The updated link also appears to be broken now.

**Comment by Oliver2213** [comment]
Fwiw, sorry and thanks for fixing this.

**Comment by towebo** [comment]
I'm sorry but when I tried the Discord invite link in the Readme, in the PR and the one in issue #5 it still says that hte invite has expired or that I don't have access.
