### ISSUE TITLE
discussion / communication method

### ISSUE THREAD

**Issue by Oliver2213** [openscape-community/openscape#5]
Hi!
Should we have a discussion method other than issues? I.E a discord where we can talk about all of this?
What real-time communication platform would people prefer? E.G. Slack, discord, irc, matrix?

**Comment by bramd** [comment]
I just went to the issues page to create this exact issue :).

Yes, I think a more informal communication channel (or channels) is needed. I would be fine with Slack or Matrix.  I haven't worked with Discord yet, but am open to that if it is accessible. Also, I think we need to keep in mind that other non-technical people might want to join (think about translations, organization structure etc). So, something that has a web client such as Slack/Matrix and can easily be joined would be good.

**Comment by steinbro** [comment]
No strong preference from me.

**Comment by Oliver2213** [comment]
Ok. I went ahead and created a discord - it has a web version and is relatively popular. Choice is loosly held; if people want something different, create and speak up.  
Join [the new openscape community server](https://discord.gg/mqzFeAPu6A)

**Comment by Oliver2213** [comment]
Discord seems to be going well so far, if quiet.

**Comment by steinbro** [comment]
Curious how people discovered it -- did you announce its creation outside of this repo?

**Comment by Oliver2213** [comment]
Yeah - I'm @coffee_nebula@hachyderm.io on mastodon; I mentioned the discord and the project for the first time on Saturday there.
